/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type { BodyType, ErrorType } from '../../api-client';

import { customInstance } from '../../api-client';
import type {
  ApiErrorResponse,
  CreateTaskRequest,
  LanesResponse,
  ListTasksParams,
  StreamEventsParams,
  TaskHistoryResponse,
  TaskListResponse,
  TaskResponse,
  TaskStatsResponse,
} from '../../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Enqueue a job. Returns the task — with its handle — before any worker runs; the submit path never waits on the work itself.
 */
export const createTask = (
  createTaskRequest: BodyType<CreateTaskRequest>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskResponse>(
    {
      url: `/api/v1/tasks`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTaskRequest,
      signal,
    },
    options,
  );
};

export const getCreateTaskMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTask>>,
    TError,
    { data: BodyType<CreateTaskRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTask>>,
  TError,
  { data: BodyType<CreateTaskRequest> },
  TContext
> => {
  const mutationKey = ['createTask'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTask>>,
    { data: BodyType<CreateTaskRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createTask(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof createTask>>>;
export type CreateTaskMutationBody = BodyType<CreateTaskRequest>;
export type CreateTaskMutationError = ErrorType<ApiErrorResponse>;

export const useCreateTask = <TError = ErrorType<ApiErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTask>>,
      TError,
      { data: BodyType<CreateTaskRequest> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTask>>,
  TError,
  { data: BodyType<CreateTaskRequest> },
  TContext
> => {
  const mutationOptions = getCreateTaskMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Your tasks, newest first. Filter by status, lane and creation date; sort and page. Returns a bare array rather than the paginated envelope the rest of this API uses — the shape is fixed by the API contract.
 */
export const listTasks = (
  params?: ListTasksParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskListResponse>(
    { url: `/api/v1/tasks`, method: 'GET', params, signal },
    options,
  );
};

export const getListTasksQueryKey = (params?: ListTasksParams) => {
  return [`/api/v1/tasks`, ...(params ? [params] : [])] as const;
};

export const getListTasksQueryOptions = <
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params?: ListTasksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTasksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTasks>>> = ({ signal }) =>
    listTasks(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTasks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListTasksQueryResult = NonNullable<Awaited<ReturnType<typeof listTasks>>>;
export type ListTasksQueryError = ErrorType<ApiErrorResponse>;

export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params: undefined | ListTasksParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTasks>>,
          TError,
          Awaited<ReturnType<typeof listTasks>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params?: ListTasksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTasks>>,
          TError,
          Awaited<ReturnType<typeof listTasks>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params?: ListTasksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params?: ListTasksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListTasksQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Your task counts per status. Every status is present, zeroed when empty.
 */
export const taskStats = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskStatsResponse>(
    { url: `/api/v1/tasks/stats`, method: 'GET', signal },
    options,
  );
};

export const getTaskStatsQueryKey = () => {
  return [`/api/v1/tasks/stats`] as const;
};

export const getTaskStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof taskStats>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof taskStats>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTaskStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof taskStats>>> = ({ signal }) =>
    taskStats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof taskStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TaskStatsQueryResult = NonNullable<Awaited<ReturnType<typeof taskStats>>>;
export type TaskStatsQueryError = ErrorType<ApiErrorResponse>;

export function useTaskStats<
  TData = Awaited<ReturnType<typeof taskStats>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof taskStats>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof taskStats>>,
          TError,
          Awaited<ReturnType<typeof taskStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTaskStats<
  TData = Awaited<ReturnType<typeof taskStats>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof taskStats>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof taskStats>>,
          TError,
          Awaited<ReturnType<typeof taskStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTaskStats<
  TData = Awaited<ReturnType<typeof taskStats>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof taskStats>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTaskStats<
  TData = Awaited<ReturnType<typeof taskStats>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof taskStats>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTaskStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * One task by its immutable id. Handles are recycled, so this is the only address that keeps pointing at the same task once it retires.
 */
export const getTaskById = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskResponse>(
    { url: `/api/v1/tasks/id/${id}`, method: 'GET', signal },
    options,
  );
};

export const getGetTaskByIdQueryKey = (id?: string) => {
  return [`/api/v1/tasks/id/${id}`] as const;
};

export const getGetTaskByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTaskById>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTaskByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskById>>> = ({ signal }) =>
    getTaskById(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTaskById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTaskByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskById>>>;
export type GetTaskByIdQueryError = ErrorType<ApiErrorResponse>;

export function useGetTaskById<
  TData = Awaited<ReturnType<typeof getTaskById>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskById>>,
          TError,
          Awaited<ReturnType<typeof getTaskById>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTaskById<
  TData = Awaited<ReturnType<typeof getTaskById>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskById>>,
          TError,
          Awaited<ReturnType<typeof getTaskById>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTaskById<
  TData = Awaited<ReturnType<typeof getTaskById>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetTaskById<
  TData = Awaited<ReturnType<typeof getTaskById>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTaskByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * One task by handle. Resolves to the active task holding that number.
 */
export const getTask = (
  handle: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskResponse>(
    { url: `/api/v1/tasks/${handle}`, method: 'GET', signal },
    options,
  );
};

export const getGetTaskQueryKey = (handle?: string) => {
  return [`/api/v1/tasks/${handle}`] as const;
};

export const getGetTaskQueryOptions = <
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTaskQueryKey(handle);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({ signal }) =>
    getTask(handle, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!handle, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTask>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getTask>>>;
export type GetTaskQueryError = ErrorType<ApiErrorResponse>;

export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTask>>,
          TError,
          Awaited<ReturnType<typeof getTask>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTask>>,
          TError,
          Awaited<ReturnType<typeof getTask>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTaskQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Take delivery of a finished task: returns the whole task with `result` populated and `collected: true`, and releases its handle number for reuse. Only a ready, not-yet-collected task can be collected — anything else is a 409.
 */
export const collectTaskResult = (
  handle: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskResponse>(
    { url: `/api/v1/tasks/${handle}/result`, method: 'GET', signal },
    options,
  );
};

export const getCollectTaskResultQueryKey = (handle?: string) => {
  return [`/api/v1/tasks/${handle}/result`] as const;
};

export const getCollectTaskResultQueryOptions = <
  TData = Awaited<ReturnType<typeof collectTaskResult>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof collectTaskResult>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCollectTaskResultQueryKey(handle);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof collectTaskResult>>> = ({ signal }) =>
    collectTaskResult(handle, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!handle, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof collectTaskResult>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CollectTaskResultQueryResult = NonNullable<
  Awaited<ReturnType<typeof collectTaskResult>>
>;
export type CollectTaskResultQueryError = ErrorType<ApiErrorResponse>;

export function useCollectTaskResult<
  TData = Awaited<ReturnType<typeof collectTaskResult>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof collectTaskResult>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof collectTaskResult>>,
          TError,
          Awaited<ReturnType<typeof collectTaskResult>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCollectTaskResult<
  TData = Awaited<ReturnType<typeof collectTaskResult>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof collectTaskResult>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof collectTaskResult>>,
          TError,
          Awaited<ReturnType<typeof collectTaskResult>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCollectTaskResult<
  TData = Awaited<ReturnType<typeof collectTaskResult>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof collectTaskResult>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useCollectTaskResult<
  TData = Awaited<ReturnType<typeof collectTaskResult>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof collectTaskResult>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCollectTaskResultQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Every transition this task went through, oldest first, with timestamps. This is where a retry’s interim failure reason and a restart’s requeue are recorded.
 */
export const getTaskHistory = (
  handle: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskHistoryResponse>(
    { url: `/api/v1/tasks/${handle}/history`, method: 'GET', signal },
    options,
  );
};

export const getGetTaskHistoryQueryKey = (handle?: string) => {
  return [`/api/v1/tasks/${handle}/history`] as const;
};

export const getGetTaskHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getTaskHistory>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskHistory>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTaskHistoryQueryKey(handle);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskHistory>>> = ({ signal }) =>
    getTaskHistory(handle, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!handle, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTaskHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTaskHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskHistory>>>;
export type GetTaskHistoryQueryError = ErrorType<ApiErrorResponse>;

export function useGetTaskHistory<
  TData = Awaited<ReturnType<typeof getTaskHistory>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskHistory>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskHistory>>,
          TError,
          Awaited<ReturnType<typeof getTaskHistory>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTaskHistory<
  TData = Awaited<ReturnType<typeof getTaskHistory>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskHistory>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskHistory>>,
          TError,
          Awaited<ReturnType<typeof getTaskHistory>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTaskHistory<
  TData = Awaited<ReturnType<typeof getTaskHistory>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskHistory>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetTaskHistory<
  TData = Awaited<ReturnType<typeof getTaskHistory>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  handle: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskHistory>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTaskHistoryQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Cancel a queued or running task — a running worker is actually aborted, not left to finish quietly. Also dismisses a failed task, which is what releases its handle number. Any other state is a 409.
 */
export const cancelTask = (
  handle: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskResponse>(
    { url: `/api/v1/tasks/${handle}/cancel`, method: 'POST', signal },
    options,
  );
};

export const getCancelTaskMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelTask>>,
    TError,
    { handle: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelTask>>,
  TError,
  { handle: string },
  TContext
> => {
  const mutationKey = ['cancelTask'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelTask>>, { handle: string }> = (
    props,
  ) => {
    const { handle } = props ?? {};

    return cancelTask(handle, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelTaskMutationResult = NonNullable<Awaited<ReturnType<typeof cancelTask>>>;

export type CancelTaskMutationError = ErrorType<ApiErrorResponse>;

export const useCancelTask = <TError = ErrorType<ApiErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelTask>>,
      TError,
      { handle: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelTask>>,
  TError,
  { handle: string },
  TContext
> => {
  const mutationOptions = getCancelTaskMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Requeue a failed task with a fresh attempt budget. `attempts` is a lifetime counter and is deliberately not reset. Only a failed task can be retried.
 */
export const retryTask = (
  handle: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskResponse>(
    { url: `/api/v1/tasks/${handle}/retry`, method: 'POST', signal },
    options,
  );
};

export const getRetryTaskMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof retryTask>>,
    TError,
    { handle: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof retryTask>>,
  TError,
  { handle: string },
  TContext
> => {
  const mutationKey = ['retryTask'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof retryTask>>, { handle: string }> = (
    props,
  ) => {
    const { handle } = props ?? {};

    return retryTask(handle, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RetryTaskMutationResult = NonNullable<Awaited<ReturnType<typeof retryTask>>>;

export type RetryTaskMutationError = ErrorType<ApiErrorResponse>;

export const useRetryTask = <TError = ErrorType<ApiErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof retryTask>>,
      TError,
      { handle: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof retryTask>>,
  TError,
  { handle: string },
  TContext
> => {
  const mutationOptions = getRetryTaskMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * What this engine can run, and the parameters each lane takes. Enough to render a submission form without hard-coding anything about a lane.
 */
export const listLanes = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LanesResponse>({ url: `/api/v1/lanes`, method: 'GET', signal }, options);
};

export const getListLanesQueryKey = () => {
  return [`/api/v1/lanes`] as const;
};

export const getListLanesQueryOptions = <
  TData = Awaited<ReturnType<typeof listLanes>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listLanes>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListLanesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listLanes>>> = ({ signal }) =>
    listLanes(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listLanes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListLanesQueryResult = NonNullable<Awaited<ReturnType<typeof listLanes>>>;
export type ListLanesQueryError = ErrorType<unknown>;

export function useListLanes<
  TData = Awaited<ReturnType<typeof listLanes>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listLanes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLanes>>,
          TError,
          Awaited<ReturnType<typeof listLanes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListLanes<
  TData = Awaited<ReturnType<typeof listLanes>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listLanes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLanes>>,
          TError,
          Awaited<ReturnType<typeof listLanes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListLanes<
  TData = Awaited<ReturnType<typeof listLanes>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listLanes>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListLanes<
  TData = Awaited<ReturnType<typeof listLanes>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listLanes>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListLanesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Server-sent stream of lifecycle events for your tasks. Every frame carries an `id`, so a browser reconnects with `Last-Event-ID` — or curl with `?since=` — and receives exactly what it missed. `accepted`, `ready`, `failed` and `cancelled` are the contract; other types are informational and may be ignored.
 */
export const streamEvents = (
  params?: StreamEventsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>({ url: `/api/v1/events`, method: 'GET', params, signal }, options);
};

export const getStreamEventsQueryKey = (params?: StreamEventsParams) => {
  return [`/api/v1/events`, ...(params ? [params] : [])] as const;
};

export const getStreamEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof streamEvents>>,
  TError = ErrorType<unknown>,
>(
  params?: StreamEventsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEvents>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStreamEventsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof streamEvents>>> = ({ signal }) =>
    streamEvents(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof streamEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StreamEventsQueryResult = NonNullable<Awaited<ReturnType<typeof streamEvents>>>;
export type StreamEventsQueryError = ErrorType<unknown>;

export function useStreamEvents<
  TData = Awaited<ReturnType<typeof streamEvents>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | StreamEventsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEvents>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamEvents>>,
          TError,
          Awaited<ReturnType<typeof streamEvents>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useStreamEvents<
  TData = Awaited<ReturnType<typeof streamEvents>>,
  TError = ErrorType<unknown>,
>(
  params?: StreamEventsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEvents>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamEvents>>,
          TError,
          Awaited<ReturnType<typeof streamEvents>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useStreamEvents<
  TData = Awaited<ReturnType<typeof streamEvents>>,
  TError = ErrorType<unknown>,
>(
  params?: StreamEventsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEvents>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useStreamEvents<
  TData = Awaited<ReturnType<typeof streamEvents>>,
  TError = ErrorType<unknown>,
>(
  params?: StreamEventsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEvents>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStreamEventsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
