/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

export interface ApiErrorResponse {
  statusCode: number;
  message: string;
  error: string;
  correlationId: string;
  /** Optional list of sub-errors */
  subErrors?: string;
}
