/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

export interface ApiErrorResponse {
  statusCode: number;
  message: string;
  error: string;
  correlationId: string;
  /** Optional list of sub-errors */
  subErrors?: string;
}
