/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

/**
 * When the key last authenticated a request; null if never used
 */
export type ApiKeyResponseLastUsedAt = string | null;
