/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */
import type { ApiKeyResponse } from './apiKeyResponse';

export interface ApiKeyPaginatedResponse {
  /** Total number of items */
  count: number;
  /** Number of items per page */
  limit: number;
  /** Page number */
  page: number;
  data: ApiKeyResponse[];
}
