/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { CancelTask200ErrorAnyOf } from './cancelTask200ErrorAnyOf';

/**
 * Populated only while `status` is `failed`, else null.
 */
export type CancelTask200Error = CancelTask200ErrorAnyOf | null;
