/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { CollectTaskResult200ErrorAnyOf } from './collectTaskResult200ErrorAnyOf';

/**
 * Populated only while `status` is `failed`, else null.
 */
export type CollectTaskResult200Error = CollectTaskResult200ErrorAnyOf | null;
