/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

export interface CreateApiKeyRequest {
  /**
   * Label so a human can tell their keys apart
   * @minLength 1
   * @maxLength 100
   */
  name: string;
}
