/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.0.0
 */

export type CreateUser201 = {
  /** Entity's id */
  id: string;
};
