/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateTaskBodyParams } from './createTaskBodyParams';

export type CreateTaskBody = {
  /**
   * A lane from GET /lanes. An unknown one is a 400.
   * @minLength 1
   */
  lane: string;
  /** Parameters for the lane’s worker. Declared params are validated against their descriptors; undeclared keys ride along untouched. */
  params?: CreateTaskBodyParams;
};
