/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Parameters for the lane’s worker. Declared params are validated against their descriptors; undeclared keys ride along untouched.
 */
export type CreateTaskRequestParams = { [key: string]: unknown };
