/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

export interface CreateApiKeyRequest {
  /**
   * Label so a human can tell their keys apart
   * @minLength 1
   * @maxLength 100
   */
  name: string;
}
