/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateApiKey201LastUsedAt } from './createApiKey201LastUsedAt';

export type CreateApiKey201 = {
  /** Entity's id */
  id: string;
  /** Label for this key */
  name: string;
  /** The leading characters of the key, so it can be identified in a list */
  prefix: string;
  /** When the key last authenticated a request; null if never used */
  lastUsedAt: CreateApiKey201LastUsedAt;
  /** Entity creation date */
  createdAt: string;
  /** The secret. Shown exactly once — it cannot be retrieved again. */
  key: string;
};
