/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

/**
 * Parameters for the lane’s worker. Declared params are validated against their descriptors; undeclared keys ride along untouched.
 */
export type CreateTaskRequestParams = { [key: string]: unknown };
