/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.0.0
 */
import type { FindUsers200DataItemRole } from './findUsers200DataItemRole';

export type FindUsers200DataItem = {
  /** Entity's id */
  id: string;
  /** Entity creation date */
  createdAt: string;
  /** Entity last update date */
  updatedAt: string;
  /** User's email address */
  email: string;
  /** User's country of residence */
  country: string;
  /** Postal code */
  postalCode: string;
  /** Street where the user is registered */
  street: string;
  /** User's role */
  role: (typeof FindUsers200DataItemRole)[keyof typeof FindUsers200DataItemRole];
};
