/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.0.0
 */

export type FindUsersParams = {
  /**
   * Specifies a limit of returned records
   * @minimum 1
   * @maximum 99999
   */
  limit?: number;
  /**
   * Page number
   * @minimum 0
   * @maximum 99999
   */
  page?: number;
  /**
   * Country of residence
   * @maxLength 50
   * @pattern ^[ A-Za-z]*$
   */
  country?: string;
  /**
   * Postal code
   * @maxLength 10
   */
  postalCode?: string;
  /**
   * Street
   * @maxLength 50
   * @pattern ^[ A-Za-z]*$
   */
  street?: string;
};
