/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.0.0
 */

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindUsers200DataItemRole = {
  admin: 'admin',
  moderator: 'moderator',
  guest: 'guest',
} as const;
