/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.0.0
 */
import type { FindUsers200DataItem } from './findUsers200DataItem';

export type FindUsers200 = {
  /** Total number of items */
  count: number;
  /** Number of items per page */
  limit: number;
  /** Page number */
  page: number;
  data: FindUsers200DataItem[];
};
