/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

export type GetTaskById200ErrorAnyOf = {
  /** Why it failed, in the worker’s own words — never a generic "failed" */
  reason: string;
  /** Whether the error is transient by nature. Stays true on a transient error that ran out of attempts, because "we stopped trying" is not "this can never work". */
  retryable: boolean;
  [key: string]: unknown;
};
