/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { GetTaskById200ErrorAnyOf } from './getTaskById200ErrorAnyOf';

/**
 * Populated only while `status` is `failed`, else null.
 */
export type GetTaskById200Error = GetTaskById200ErrorAnyOf | null;
