/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Whatever the submitter sent, normalised against the lane’s descriptors
 */
export type GetTask200Params = { [key: string]: unknown };
