/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { GetTaskHistory200ItemDetail } from './getTaskHistory200ItemDetail';

export type GetTaskHistory200Item = {
  /** Monotonic per database. Doubles as the SSE cursor. */
  id: number;
  /** accepted | started | ready | failed | cancelled, plus informational types (retry_scheduled, requeued_on_restart, lease_expired, collected, retry_requested) */
  type: string;
  /** When the transition was recorded */
  at: string;
  /** Type-specific context: the reason, the attempt number, the backoff… */
  detail: GetTaskHistory200ItemDetail;
};
