/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Health Check Succeeded
 */
export interface HealthResponse {
  status: string;
}
