/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */
import type { LaneParamType } from './laneParamType';

export interface LaneParam {
  name: string;
  type: (typeof LaneParamType)[keyof typeof LaneParamType];
  required: boolean;
  /** Applied when the caller omits it */
  default?: unknown;
  description?: string;
  /** Inclusive lower bound, numbers only */
  min?: number;
  /** Inclusive upper bound, numbers only */
  max?: number;
}
