/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { LaneParam } from './laneParam';

export interface LaneResponse {
  lane: string;
  /** How the worker is dispatched */
  kind: string;
  description?: string;
  params: LaneParam[];
}
