/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LaneParamType = { number: 'number', boolean: 'boolean', string: 'string' } as const;
