/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { ListTasks200ItemErrorAnyOf } from './listTasks200ItemErrorAnyOf';

/**
 * Populated only while `status` is `failed`, else null.
 */
export type ListTasks200ItemError = ListTasks200ItemErrorAnyOf | null;
