/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

import type { ListTasksSort } from './listTasksSort';
import type { TaskStatus } from './taskStatus';

export type ListTasksParams = {
  /**
   * Where a task is in its lifecycle
   */
  status?: TaskStatus;
  /**
   * Filter by lane
   */
  lane?: string;
  /**
   * Only tasks created at or after this instant (ISO 8601)
   */
  from?: string;
  /**
   * Only tasks created at or before this instant (ISO 8601)
   */
  to?: string;
  /**
   * By creation time. Defaults to `desc` — newest first.
   */
  sort?: (typeof ListTasksSort)[keyof typeof ListTasksSort];
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number;
};
