/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { ListLanes200ItemParamsItem } from './listLanes200ItemParamsItem';

export type ListLanes200Item = {
  lane: string;
  /** How the worker is dispatched */
  kind: string;
  description?: string;
  params: ListLanes200ItemParamsItem[];
};
