/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

export type ListApiKeysParams = {
  /**
   * Specifies a limit of returned records
   * @minimum 1
   * @maximum 99999
   */
  limit?: number;
  /**
   * Page number
   * @minimum 0
   * @maximum 99999
   */
  page?: number;
};
