/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { ListLanes200ItemParamsItemType } from './listLanes200ItemParamsItemType';

export type ListLanes200ItemParamsItem = {
  name: string;
  type: (typeof ListLanes200ItemParamsItemType)[keyof typeof ListLanes200ItemParamsItemType];
  required: boolean;
  /** Applied when the caller omits it */
  default?: unknown;
  description?: string;
  /** Inclusive lower bound, numbers only */
  min?: number;
  /** Inclusive upper bound, numbers only */
  max?: number;
};
