/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { ListApiKeys200DataItem } from './listApiKeys200DataItem';

export type ListApiKeys200 = {
  /** Total number of items */
  count: number;
  /** Number of items per page */
  limit: number;
  /** Page number */
  page: number;
  data: ListApiKeys200DataItem[];
};
