/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

import type { ListTasks200ItemError } from './listTasks200ItemError';
import type { ListTasks200ItemParams } from './listTasks200ItemParams';
import type { ListTasks200ItemStatus } from './listTasks200ItemStatus';

export type ListTasks200Item = {
  /** Stable identity. Handles are recycled, so `scrape-1` may name three different tasks over an afternoon; this never changes and addresses retired tasks too. */
  id: string;
  /** Short human-friendly name, `<lane>-<n>`, numbered per lane and recycled */
  handle: string;
  /** Which worker runs this task */
  lane: string;
  /** Whatever the submitter sent, normalised against the lane’s descriptors */
  params: ListTasks200ItemParams;
  /** Where a task is in its lifecycle */
  status: (typeof ListTasks200ItemStatus)[keyof typeof ListTasks200ItemStatus];
  /** The worker’s output. Populated only while `status` is `ready`, else null. */
  result: unknown;
  /** Populated only while `status` is `failed`, else null. */
  error: ListTasks200ItemError;
  /** Lifetime execution count — one per claim, never reset. A manual retry extends the budget instead, so this stays honest about how much work a task has cost. */
  attempts: number;
  /** Flips to true once the result is retrieved, which releases the handle number */
  collected: boolean;
  /** Fixture data for the dashboard. Seed rows are excluded from the claim query and from both recovery sweeps, so a seeded `running` task never executes. */
  is_seed: boolean;
  /** When the task was accepted */
  created_at: string;
  /** Last state change */
  updated_at: string;
};
