/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

export type ListApiKeysParams = {
  /**
   * Specifies a limit of returned records
   * @minimum 1
   * @maximum 99999
   */
  limit?: number;
  /**
   * Page number
   * @minimum 0
   * @maximum 99999
   */
  page?: number;
};
