/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { ListApiKeys200DataItemLastUsedAt } from './listApiKeys200DataItemLastUsedAt';

export type ListApiKeys200DataItem = {
  /** Entity's id */
  id: string;
  /** Label for this key */
  name: string;
  /** The leading characters of the key, so it can be identified in a list */
  prefix: string;
  /** When the key last authenticated a request; null if never used */
  lastUsedAt: ListApiKeys200DataItemLastUsedAt;
  /** Entity creation date */
  createdAt: string;
};
