/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

export type LoginBody = {
  /**
   * Email address, used as the login identifier
   * @minLength 5
   * @maxLength 320
   */
  email: string;
  /**
   * Plaintext password. Sent once, stored only as a scrypt hash.
   * @minLength 8
   * @maxLength 256
   */
  password: string;
};
