/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

import type { Me200Kind } from './me200Kind';
import type { Me200User } from './me200User';

export type Me200 = {
  user: Me200User;
  /** Which credential authenticated this request */
  kind: (typeof Me200Kind)[keyof typeof Me200Kind];
};
