/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

export type Me200User = {
  /** Entity's id */
  id: string;
  /** Entity creation date */
  createdAt: string;
  /** Entity last update date */
  updatedAt: string;
  /** User's email address */
  email: string;
  /** User's display name */
  name: string;
};
