/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

import type { MeResponseKind } from './meResponseKind';
import type { UserResponse } from './userResponse';

export interface MeResponse {
  user: UserResponse;
  /** Which credential authenticated this request */
  kind: (typeof MeResponseKind)[keyof typeof MeResponseKind];
}
