/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

import type { MeResponseKind } from './meResponseKind';
import type { UserResponse } from './userResponse';

export interface MeResponse {
  user: UserResponse;
  /** Which credential authenticated this request */
  kind: (typeof MeResponseKind)[keyof typeof MeResponseKind];
}
