/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { UserResponse } from './userResponse';

export interface SessionResponse {
  user: UserResponse;
  /** Session JWT. Also set as an HttpOnly cookie on this response. */
  token: string;
  /** Token lifetime in seconds */
  expiresIn: number;
}
