/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

export interface SignupRequest {
  /**
   * Email address, used as the login identifier
   * @minLength 5
   * @maxLength 320
   */
  email: string;
  /**
   * Display name
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Plaintext password. Sent once, stored only as a scrypt hash.
   * @minLength 8
   * @maxLength 256
   */
  password: string;
}
