/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */
import type { Signup201User } from './signup201User';

export type Signup201 = {
  user: Signup201User;
  /** Session JWT. Also set as an HttpOnly cookie on this response. */
  token: string;
  /** Token lifetime in seconds */
  expiresIn: number;
};
