/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

export type StreamEventsParams = {
  /**
   * Replay every event after this id before streaming live ones. A browser sends the `Last-Event-ID` header instead and does not need this; it is here so a curl client can replay too. The header wins when both are present.
   * @minimum 0
   */
  since?: number;
};
