/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type-specific context: the reason, the attempt number, the backoff…
 */
export type TaskEventResponseDetail = { [key: string]: unknown };
