/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

export interface TaskError {
  /** Why it failed, in the worker’s own words — never a generic "failed" */
  reason: string;
  /** Whether the error is transient by nature. Stays true on a transient error that ran out of attempts, because "we stopped trying" is not "this can never work". */
  retryable: boolean;
  [key: string]: unknown;
}
