/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

/**
 * Where a task is in its lifecycle
 */
// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskStatus = {
  queued: 'queued',
  running: 'running',
  ready: 'ready',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];
