/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */
import type { TaskError } from './taskError';

/**
 * Populated only while `status` is `failed`, else null.
 */
export type TaskResponseError = TaskError | null;
