/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */
import type { TaskEventResponseDetail } from './taskEventResponseDetail';

export interface TaskEventResponse {
  /** Monotonic per database. Doubles as the SSE cursor. */
  id: number;
  /** accepted | started | ready | failed | cancelled, plus informational types (retry_scheduled, requeued_on_restart, lease_expired, collected, retry_requested) */
  type: string;
  /** When the transition was recorded */
  at: string;
  /** Type-specific context: the reason, the attempt number, the backoff… */
  detail: TaskEventResponseDetail;
}
