/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Job Runner API
 * Submit background work, watch it run, collect the result.
 * OpenAPI spec version: 0.0.0
 */

export interface UserResponse {
  /** Entity's id */
  id: string;
  /** Entity creation date */
  createdAt: string;
  /** Entity last update date */
  updatedAt: string;
  /** User's email address */
  email: string;
  /** User's display name */
  name: string;
}
