/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * web-app-template API
 * REST API for web-app-template.
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type { BodyType, ErrorType } from '../../api-client';

import { customInstance } from '../../api-client';
import type {
  ApiErrorResponse,
  CreateApiKey201,
  CreateApiKeyBody,
  ListApiKeys200,
  ListApiKeysParams,
} from '../../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List your active API keys. Never returns the secret.
 */
export const listApiKeys = (
  params?: ListApiKeysParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListApiKeys200>(
    { url: `/api/v1/keys`, method: 'GET', params, signal },
    options,
  );
};

export const getListApiKeysQueryKey = (params?: ListApiKeysParams) => {
  return [`/api/v1/keys`, ...(params ? [params] : [])] as const;
};

export const getListApiKeysQueryOptions = <
  TData = Awaited<ReturnType<typeof listApiKeys>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params?: ListApiKeysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeys>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListApiKeysQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listApiKeys>>> = ({ signal }) =>
    listApiKeys(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listApiKeys>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof listApiKeys>>>;
export type ListApiKeysQueryError = ErrorType<ApiErrorResponse>;

export function useListApiKeys<
  TData = Awaited<ReturnType<typeof listApiKeys>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params: undefined | ListApiKeysParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeys>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApiKeys>>,
          TError,
          Awaited<ReturnType<typeof listApiKeys>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListApiKeys<
  TData = Awaited<ReturnType<typeof listApiKeys>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params?: ListApiKeysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeys>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApiKeys>>,
          TError,
          Awaited<ReturnType<typeof listApiKeys>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListApiKeys<
  TData = Awaited<ReturnType<typeof listApiKeys>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params?: ListApiKeysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeys>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListApiKeys<
  TData = Awaited<ReturnType<typeof listApiKeys>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  params?: ListApiKeysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listApiKeys>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListApiKeysQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create an API key. The secret is returned once and never again.
 */
export const createApiKey = (
  createApiKeyBody: BodyType<CreateApiKeyBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CreateApiKey201>(
    {
      url: `/api/v1/keys`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createApiKeyBody,
      signal,
    },
    options,
  );
};

export const getCreateApiKeyMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createApiKey>>,
    TError,
    { data: BodyType<CreateApiKeyBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createApiKey>>,
  TError,
  { data: BodyType<CreateApiKeyBody> },
  TContext
> => {
  const mutationKey = ['createApiKey'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createApiKey>>,
    { data: BodyType<CreateApiKeyBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createApiKey(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof createApiKey>>>;
export type CreateApiKeyMutationBody = BodyType<CreateApiKeyBody>;
export type CreateApiKeyMutationError = ErrorType<ApiErrorResponse>;

export const useCreateApiKey = <TError = ErrorType<ApiErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createApiKey>>,
      TError,
      { data: BodyType<CreateApiKeyBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createApiKey>>,
  TError,
  { data: BodyType<CreateApiKeyBody> },
  TContext
> => {
  const mutationOptions = getCreateApiKeyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Revoke an API key. The row is kept so its history stays auditable.
 */
export const revokeApiKey = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return customInstance<void>({ url: `/api/v1/keys/${id}`, method: 'DELETE' }, options);
};

export const getRevokeApiKeyMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof revokeApiKey>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof revokeApiKey>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['revokeApiKey'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeApiKey>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return revokeApiKey(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RevokeApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof revokeApiKey>>>;

export type RevokeApiKeyMutationError = ErrorType<ApiErrorResponse>;

export const useRevokeApiKey = <TError = ErrorType<ApiErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof revokeApiKey>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof revokeApiKey>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getRevokeApiKeyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
